services:
  postgres:
    image: postgres:15
    container_name: fitness-club-db
    environment:
      POSTGRES_DB: fitnessclub
      POSTGRES_USER: fitnessclub
      POSTGRES_PASSWORD: fitnessclub123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
